/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-1",
    "aws_cognito_identity_pool_id": "us-west-1:5e491f64-01d9-40af-aeb1-23a90412f275",
    "aws_cognito_region": "us-west-1",
    "aws_user_pools_id": "us-west-1_06o76S2Mc",
    "aws_user_pools_web_client_id": "8nlocco9r4bp5bqva7jt7io76",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "penrynflowerfarmbucket193022-dev",
    "aws_user_files_s3_bucket_region": "us-west-1",
    "aws_appsync_graphqlEndpoint": "https://2qdtwrhx3vgpdacpmxg62swjge.appsync-api.us-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-kladsj5rfvaitf3mpmr32ibavy"
};


export default awsmobile;
