/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-1",
    "aws_appsync_graphqlEndpoint": "https://oscdepw3ungo5bjuiv2sgs44li.appsync-api.us-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-nkj55hulrbgonoph5c6acux64e",
    "aws_cognito_identity_pool_id": "us-west-1:71d23cd0-ce27-4df9-81f8-d0617444305b",
    "aws_cognito_region": "us-west-1",
    "aws_user_pools_id": "us-west-1_W4fncjcbg",
    "aws_user_pools_web_client_id": "6os625qd685fidvhjqjht2s6tc",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "penrynflowerfarmbucket195050-staging",
    "aws_user_files_s3_bucket_region": "us-west-1"
};


export default awsmobile;
